# Generated by Django 3.2.8 on 2021-10-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_info',
            fields=[
                ('accountinfoid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'accountinfo_table',
            },
        ),
    ]
