# Generated by Django 3.2.8 on 2021-10-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbill_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=45)),
                ('payment_sched', models.CharField(max_length=45)),
                ('posted_on', models.CharField(max_length=45)),
                ('posted_by', models.TextField(default=' ')),
            ],
            options={
                'db_table': 'billinfo',
            },
        ),
        migrations.CreateModel(
            name='company_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('zipcode', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'companyinfo',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumerlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, max_length=45, null=True)),
                ('meter_number', models.CharField(blank=True, max_length=45, null=True)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('meter_num', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('acc_id', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('cell_num', models.CharField(max_length=45)),
                ('zipcode', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'customerinfo',
            },
        ),
        migrations.CreateModel(
            name='latest_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_reading', models.FloatField(max_length=45)),
                ('prev_reading', models.FloatField(max_length=45)),
                ('usage', models.FloatField(max_length=45)),
                ('bill', models.FloatField(max_length=45)),
                ('penalty', models.FloatField(max_length=45)),
                ('total_bill', models.FloatField(max_length=45)),
                ('prev_due', models.FloatField(max_length=45)),
            ],
            options={
                'db_table': 'latestbill',
            },
        ),
        migrations.CreateModel(
            name='months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commulative_bill', models.FloatField(max_length=45)),
                ('reading', models.FloatField(max_length=45)),
                ('usage', models.FloatField(max_length=45)),
                ('bill', models.FloatField(max_length=45)),
                ('penalty', models.FloatField(max_length=45)),
                ('total_bill', models.FloatField(max_length=45)),
            ],
            options={
                'db_table': 'months',
            },
        ),
        migrations.CreateModel(
            name='signin',
            fields=[
                ('meter_num', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='usage_and_payment_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(max_length=45)),
                ('years', models.BigIntegerField()),
            ],
            options={
                'db_table': 'usage_and_payment_history',
            },
        ),
        migrations.DeleteModel(
            name='account_info',
        ),
    ]
