# Generated by Django 3.2.8 on 2021-10-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterbill_app', '0002_auto_20211028_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bill_info',
        ),
        migrations.DeleteModel(
            name='company_info',
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.DeleteModel(
            name='customer_info',
        ),
        migrations.DeleteModel(
            name='latest_bill',
        ),
        migrations.DeleteModel(
            name='months',
        ),
        migrations.DeleteModel(
            name='signin',
        ),
        migrations.DeleteModel(
            name='usage_and_payment_history',
        ),
        migrations.AlterModelTable(
            name='consumerlist',
            table='consumerinfo',
        ),
    ]
