# Generated by Django 3.2.8 on 2021-10-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbill_app', '0006_auto_20211028_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerlist',
            name='account_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='consumerlist',
            name='meter_number',
            field=models.CharField(default=' ', max_length=45, primary_key=True, serialize=False),
        ),
    ]
