from django.db import models
from django.utils import timezone
from datetime import date
# Create your models here.

class Consumerlist(models.Model):
     account_id = models.CharField(max_length = 45, primary_key = True)
     meter_number = models.CharField(max_length = 45, blank = True, null = True)
     first_name = models.CharField(max_length = 45, blank = True, null = True)
     middle_name = models.CharField(max_length = 45, blank = True, null = True)
     last_name = models.CharField(max_length = 45, blank = True, null = True)
     address = models.CharField(max_length = 45, blank = True, null = True)

     class Meta:
         db_table = 'consumerinfo'


class usagerecord(models.Model):

    current_date = date.today()
    
    accountid = models.CharField(max_length=45,primary_key=True)
    rateid = models.CharField(max_length=45,default= " ")
    prevyeardue = models.FloatField(default = 0)
    excesspayment = models.FloatField(default = 0)
    commulative_bill = models.FloatField(default = 0)
    year = models.BigIntegerField(default=current_date.year)
    consumerid = models.ForeignKey(Consumerlist,on_delete = models.CASCADE,default="")
    accountinfoid = models.CharField(max_length = 50,default = "")
    amountpaid_history = models.TextField(default = "")
    datepaid_history = models.TextField(default = "")
    postedby_history = models.TextField(default = "")
    or_number_history = models.TextField(default = "")
    previous_reading = models.FloatField(default = 0)



    #january
    reading_jan = models.FloatField(default = 0)
    reading_date_jan = models.CharField(max_length=45,default = " ")
    reading_postedby_jan = models.CharField(max_length=45,default = " ")
    usage_jan = models.FloatField(default = 0)
    penalty_jan = models.FloatField(default = 0)
    bill_jan = models.FloatField(default = 0)
    totalbill_jan = models.FloatField(default = 0)
    paidamt_jan = models.FloatField(default = 0)
    datepaid_jan = models.TextField(default = " ")
    dateposted_jan = models.CharField(max_length=45,default = " ")
    postedby_jan = models.TextField(default = " ")
    txrefnum_jan = models.CharField(max_length=45,default = " ")
    ior_jan = models.CharField(max_length=50,default=" ")
    amountpaid_str_jan = models.TextField(default="")
    #february
    reading_feb = models.FloatField(default = 0)
    reading_date_feb = models.CharField(max_length=45)
    reading_postedby_feb = models.CharField(max_length=45)
    usage_feb = models.FloatField(default = 0)
    penalty_feb = models.FloatField(default = 0)
    bill_feb = models.FloatField(default = 0)
    totalbill_feb = models.FloatField(default = 0)
    paidamt_feb = models.FloatField(default = 0)
    datepaid_feb = models.TextField(default = " ")
    dateposted_feb = models.CharField(max_length=45,default = " ")
    postedby_feb = models.TextField(default=" ")
    txrefnum_feb = models.CharField(max_length=45,default = " ")
    ior_feb = models.CharField(max_length=50,default=" ")
    amountpaid_str_feb = models.TextField(default="")
    #march
    reading_mar = models.FloatField(default = 0)
    reading_date_mar = models.CharField(max_length=45)
    reading_postedby_mar = models.CharField(max_length=45)
    usage_mar = models.FloatField(default = 0)
    penalty_mar = models.FloatField(default = 0)
    bill_mar = models.FloatField(default = 0)
    totalbill_mar = models.FloatField(default = 0)
    paidamt_mar = models.FloatField(default = 0)
    datepaid_mar = models.TextField(default = " ")
    dateposted_mar = models.TextField(default = " ")
    postedby_mar = models.TextField(default=" ")
    txrefnum_mar = models.CharField(max_length=45,default = " ")
    ior_mar = models.CharField(max_length=50,default=" ")
    amountpaid_str_mar = models.TextField(default ="")
    #april
    reading_apr = models.FloatField(default = 0)
    reading_date_apr = models.CharField(max_length=45)
    reading_postedby_apr = models.CharField(max_length=45)
    usage_apr = models.FloatField(default = 0)
    penalty_apr = models.FloatField(default = 0)
    bill_apr = models.FloatField(default = 0)
    totalbill_apr = models.FloatField(default = 0)
    paidamt_apr = models.FloatField(default = 0)
    datepaid_apr = models.TextField(default = " ")
    dateposted_apr = models.CharField(max_length=45,default = " ")
    postedby_apr = models.TextField(default=" ")
    txrefnum_apr = models.CharField(max_length=45,default = " ")
    ior_apr = models.CharField(max_length=50,default=" ")
    amountpaid_str_apr = models.TextField(default="")
    #may
    reading_may = models.FloatField(default = 0)
    reading_date_may = models.CharField(max_length=45)
    reading_postedby_may = models.CharField(max_length=45)
    usage_may = models.FloatField(default = 0)
    penalty_may = models.FloatField(default = 0)
    bill_may = models.FloatField(default = 0)
    totalbill_may = models.FloatField(default = 0)
    paidamt_may = models.FloatField(default = 0)
    datepaid_may = models.TextField(default = " ")
    dateposted_may = models.CharField(max_length=45,default = " ")
    postedby_may = models.TextField(default=" ")
    txrefnum_may = models.CharField(max_length=45,default = " ")
    ior_may = models.CharField(max_length=50,default=" ")
    amountpaid_str_may = models.TextField(default="")
    #june
    reading_jun = models.FloatField(default = 0)
    reading_date_jun = models.CharField(max_length=45)
    reading_postedby_jun = models.CharField(max_length=45)
    usage_jun = models.FloatField(default = 0)
    penalty_jun = models.FloatField(default = 0)
    bill_jun = models.FloatField(default = 0)
    totalbill_jun = models.FloatField(default = 0)
    paidamt_jun = models.FloatField(default = 0)
    datepaid_jun = models.TextField(default = " ")
    dateposted_jun = models.CharField(max_length=45,default = " ")
    postedby_jun = models.TextField(default=" ")
    txrefnum_jun = models.CharField(max_length=45,default = " ")
    ior_jun = models.CharField(max_length=50,default=" ")
    amountpaid_str_jun = models.TextField(default="")
    #july
    reading_jul = models.FloatField(default = 0)
    reading_date_jul = models.CharField(max_length=45)
    reading_postedby_jul = models.CharField(max_length=45)
    usage_jul = models.FloatField(default = 0)
    penalty_jul = models.FloatField(default = 0)
    bill_jul = models.FloatField(default = 0)
    totalbill_jul = models.FloatField(default = 0)
    paidamt_jul = models.FloatField(default = 0)
    datepaid_jul = models.TextField(default = " ")
    dateposted_jul = models.CharField(max_length=45,default = " ")
    postedby_jul = models.TextField(default=" ")
    txrefnum_jul = models.CharField(max_length=45,default = " ")
    ior_jul = models.CharField(max_length=50,default=" ")
    amountpaid_str_jul = models.TextField(default="")
    #august
    reading_aug = models.FloatField(default = 0)
    reading_date_aug = models.CharField(max_length=45)
    reading_postedby_aug = models.CharField(max_length=45)
    usage_aug = models.FloatField(default = 0)
    penalty_aug = models.FloatField(default = 0)
    bill_aug = models.FloatField(default = 0)
    totalbill_aug = models.FloatField(default = 0)
    paidamt_aug = models.FloatField(default = 0)
    datepaid_aug = models.TextField(default = " ")
    dateposted_aug = models.CharField(max_length=45,default = " ")
    postedby_aug = models.TextField(default=" ")
    txrefnum_aug = models.CharField(max_length=45,default = " ")
    ior_aug = models.CharField(max_length=50,default=" ")
    amountpaid_str_aug = models.TextField(default="")
    #september
    reading_sept = models.FloatField(default = 0)
    reading_date_sept = models.CharField(max_length=45)
    reading_postedby_sept = models.CharField(max_length=45)
    usage_sept = models.FloatField(default = 0)
    penalty_sept = models.FloatField(default = 0)
    bill_sept = models.FloatField(default = 0)
    totalbill_sept = models.FloatField(default = 0)
    paidamt_sept = models.FloatField(default = 0)
    datepaid_sept = models.TextField(default = " ")
    dateposted_sept = models.CharField(max_length=45,default = " ")
    postedby_sept = models.TextField(default=" ")
    txrefnum_sept = models.CharField(max_length=45,default = " ")
    ior_sept = models.CharField(max_length=50,default=" ")
    amountpaid_str_sept = models.TextField(default="")
    #october
    reading_oct = models.FloatField(default = 0)
    reading_date_oct = models.CharField(max_length=45)
    reading_postedby_oct = models.CharField(max_length=45)
    usage_oct = models.FloatField(default = 0)
    penalty_oct = models.FloatField(default = 0)
    bill_oct = models.FloatField(default = 0)
    totalbill_oct = models.FloatField(default = 0)
    paidamt_oct = models.FloatField(default = 0)
    datepaid_oct = models.TextField(default = " ")
    dateposted_oct = models.CharField(max_length=45,default = " ")
    postedby_oct = models.TextField(default=" ")
    txrefnum_oct = models.TextField(default = " ")
    ior_oct = models.CharField(max_length=50,default=" ")
    amountpaid_str_oct = models.TextField(default="")
    #november
    reading_nov = models.FloatField(default = 0)
    reading_date_nov = models.CharField(max_length=45)
    reading_postedby_nov = models.CharField(max_length=45)
    usage_nov = models.FloatField(default = 0)
    penalty_nov = models.FloatField(default = 0)
    bill_nov = models.FloatField(default = 0)
    totalbill_nov = models.FloatField(default = 0)
    paidamt_nov = models.FloatField(default = 0)
    datepaid_nov = models.TextField(default = " ")
    dateposted_nov = models.CharField(max_length=45,default = " ")
    postedby_nov = models.TextField(default=" ")
    txrefnum_nov = models.CharField(max_length=45,default = " ")
    ior_nov = models.CharField(max_length=50,default=" ")
    amountpaid_str_nov = models.TextField(default="")
    #december
    reading_dec = models.FloatField(default = 0)
    reading_date_dec = models.CharField(max_length=45)
    reading_postedby_dec = models.CharField(max_length=45)
    usage_dec = models.FloatField(default = 0)
    penalty_dec = models.FloatField(default = 0)
    bill_dec = models.FloatField(default = 0)
    totalbill_dec = models.FloatField(default = 0)
    paidamt_dec = models.FloatField(default = 0)
    datepaid_dec = models.TextField(default = " ")
    dateposted_dec = models.CharField(max_length=45,default = " ")
    postedby_dec = models.TextField(default=" ")
    txrefnum_dec = models.CharField(max_length=45,default = " ")
    ior_dec = models.CharField(max_length=50,default=" ")
    amountpaid_str_dec = models.TextField(default="")


    class Meta:
        db_table = "accountrecord"
